CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	session_token TEXT UNIQUE,
	created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

ALTER TABLE todos ADD COLUMN owner_id INTEGER NOT NULL DEFAULT 1 REFERENCES users(id);
ALTER TABLE todos ADD COLUMN is_public INTEGER NOT NULL DEFAULT 0;
