CREATE TABLE IF NOT EXISTS todo_steps (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	todo_id INTEGER NOT NULL REFERENCES todos(id) ON DELETE CASCADE,
	title TEXT NOT NULL,
	completed INTEGER NOT NULL DEFAULT 0,
	sort_order INTEGER NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
