CREATE TABLE IF NOT EXISTS tag_groups (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	owner_id INTEGER NOT NULL REFERENCES users(id),
	sort_order INTEGER NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS tags (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	group_id INTEGER REFERENCES tag_groups(id) ON DELETE SET NULL,
	owner_id INTEGER NOT NULL REFERENCES users(id),
	color TEXT NOT NULL DEFAULT '#0E838F',
	created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS todo_tags (
	todo_id INTEGER NOT NULL REFERENCES todos(id) ON DELETE CASCADE,
	tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
	PRIMARY KEY (todo_id, tag_id)
);
